version: "3.8"

# Docker Compose overrides for development environments
services:
  # frontend:
  #   build:
  #     args:
  #       OPENDC_API_BASE_URL: http://localhost:8081
  #   ports:
  #     - "8080:80"

  # api:
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SENTRY_ENVIRONMENT: "development"

  simulator:
    environment:
      SENTRY_ENVIRONMENT: "development"

  mongo:
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: on-failure
    networks:
      - backend
    depends_on:
      - mongo
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
